const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const base=process.env.SPACOLOGY_BASE_URL||'http://127.0.0.1:4173';
const url=base+'/prototypes/spacology-v0.1.0.html';
(async()=>{
 const browser=await chromium.launch({headless:process.env.SPACOLOGY_HEADED !== '1'});const failures=[];
 async function test(name,fn){const context=await browser.newContext({viewport:{width:1024,height:768},serviceWorkers:'block'});const p=await context.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
  const state=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('spacologyRunV010')));
  async function seed(changes={}){await p.goto(url);await p.evaluate(changes=>{const s=JSON.parse(localStorage.getItem('spacologyRunV010'));Object.assign(s,{field:['Tarn',null,null,null,null],support:Array(7).fill(null),reserve:[],gear:[],equipped:{},shipEquipped:[],gold:42,scrap:0,crystals:0,pack:null,packOffers:['rot','tempo','bulwark'],packRefreshes:0},changes);localStorage.setItem('spacologyRunV010',JSON.stringify(s));},changes);await p.reload();await p.locator('#enterOps').click()}
  async function battle(){await p.locator('#continueButton').click();await p.waitForURL('**/watchable-fight.html**');await p.evaluate(()=>cancelSessionAutostart())}
  try{await fn({p,state,seed,battle});assert.deepEqual(errors,[]);console.log('PASS',name)}catch(e){console.error('FAIL',name,e.message);failures.push(name+': '+e.message)}finally{await context.close()}}
 await test('five/seven cells migrate overflow without losing crew or gear',async({p,state,seed})=>{await seed({field:[null,null,null,null,'Tarn',null,'Ash',null],support:[null,null,null,null,null,null,'Quill','Coda'],equipped:{Ash:['Bore Bit']}});const s=await state();assert.equal(s.field.length,5);assert.equal(s.support.length,7);assert.equal(s.field[4],'Tarn');assert.equal(s.support[6],'Quill');assert(s.reserve.includes('Ash')&&s.reserve.includes('Coda'));assert.deepEqual(s.equipped.Ash,['Bore Bit']);assert.equal(await p.locator('.crew-row').first().locator('.slot,.unit').count(),5);assert.equal(await p.locator('.crew-row').last().locator('.slot,.unit').count(),7)});
 await test('pack receipt is compact; preview and reload preserve paid contents',async({p,state,seed})=>{await seed();await p.locator('[data-open="rot"]').click();assert.equal(await p.locator('.reward-card').count(),5);assert.match(await p.locator('.open-summary p').textContent(),/credited/);const before=await state();await p.locator('[data-card-select]').first().click();assert(await p.locator('#overlay').evaluate(el=>el.classList.contains('open')));assert.equal((await state()).gold,before.gold);await p.reload();await p.locator('#enterOps').click();assert.deepEqual((await state()).pack,before.pack);assert.equal((await state()).gold,before.gold);await p.locator('#takeAll').click();assert.equal((await state()).pack,null);assert(await p.locator('#packSelect').isVisible());const layout=await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth);assert(layout)});
 await test('automatic sale and migrated scrap preference preserve the original roster',async({p,state,seed})=>{for(const policy of ['sell','scrap']){await seed({duplicatePolicy:policy,reserve:['Ash','Quill','Maul','Bosk','Coda','Morrow','Spore'],scrap:0,gold:42,pack:null});await p.evaluate(()=>Math.random=()=>.5);await p.locator('[data-open="rot"]').click();const s=await state();assert.equal(s.reserve.length,7);assert.equal(s.field[0],'Tarn');assert.equal(s.pack.resolved.slice(5).filter(Boolean).length,2);assert.equal(s.gold,41);assert.equal(s.scrap,4);await p.locator('#disposeRemaining').click();assert((await state()).gold<42)}});
 await test('drag recipe consumes only loose inputs and crafted gear affects combat',async({p,state,seed,battle})=>{await seed({field:['Morrow',null,null,null,null],gear:['Tuning Fork','Spore Sling'],scrap:8});await p.locator('[data-tab="gear"]').click();await p.locator('.item[data-item="Tuning Fork"]').dragTo(p.locator('.item[data-item="Spore Sling"]'));assert.equal(await p.locator('#modalBody h2').textContent(),'Resonance Coil');await p.locator('[data-craft="Resonance Coil"]').click();assert.deepEqual((await state()).gear,['Resonance Coil']);assert.equal((await state()).scrap,0);assert.equal((await state()).gold,42);await p.locator('#closeModal').click();await p.locator('.item[data-item="Resonance Coil"]').dragTo(p.locator('.unit[data-unit="Morrow"]'));assert.deepEqual((await state()).equipped.Morrow,['Resonance Coil']);await battle();const u=await p.evaluate(()=>{const u=G.units.find(x=>x.n==='Morrow');return {frac:u.frac,spread:u.spreadExtra,e:u.e}});assert.deepEqual(u,{frac:3,spread:1,e:'growth'})});
 await test('copy recruitment charges per copy and merges owned crew',async({p,state,seed})=>{await seed({crystals:4});assert.equal(await p.locator('[data-info="barracks"]').count(),0);await p.locator('[data-info="attune"]').click();await p.locator('[data-create-copy="Tarn"]').click();assert.equal((await state()).crystals,2);assert.equal((await state()).crewCopies.length,1);await p.locator('[data-create-copy="Tarn"]').click();assert.equal((await state()).crystals,0);assert.equal((await state()).crewUpgrades.Tarn,1);assert.equal((await state()).crewCopies.length,0);assert(await p.locator('[data-create-copy="Tarn"]').isDisabled())});
 await test('copy rank and ancestral harmony match displayed and real battle stats',async({p,state,seed,battle})=>{await seed({support:['Maul','Quill',null,null,null,null,null],crystals:4});await p.locator('[data-info="attune"]').click();await p.locator('[data-create-copy="Tarn"]').click();await p.locator('[data-create-copy="Tarn"]').click();assert.equal((await state()).crewUpgrades.Tarn,1);assert.equal((await state()).crystals,0);await p.locator('#closeModal').click();assert.match(await p.locator('[data-planet-harmony="Earth"]').textContent(),/3/);await p.locator('.unit[data-unit="Tarn"]').click();const hp=Number(await p.locator('.kit-stats div').first().locator('b').textContent());assert.equal(hp,205);await p.locator('#closeModal').click();await battle();assert.equal(await p.evaluate(()=>G.units.find(u=>u.n==='Tarn').max),hp)});
 await test('selected goal and modifier alter combat conditions and reward',async({p,state,seed,battle})=>{await seed();await p.locator('[data-info="calls"]').click();await p.locator('[data-goal="resonance"]').click();await p.locator('#closeModal').click();await p.locator('[data-info="modifiers"]').click();await p.locator('[data-modifier="reinforced"]').click();assert.deepEqual((await state()).modifiers,['reinforced']);assert(await p.locator('[data-modifier="volatile"]').isDisabled());await p.locator('#closeModal').click();await battle();assert.equal(await p.evaluate(()=>G.pool[0].hp),Math.round(52*1.25));assert.match(await p.locator('.session-objective').textContent(),/Resonance|RESONANCE/);await p.evaluate(()=>{G.breaks=2;G.chains=0;G.units=G.units.filter(u=>u.side==='ally').concat(G.pool.map((p,i)=>({id:'f'+i,side:'foe',alive:false,hp:0})));G.spawned=G.pool.length;finish('Crew wins')});const r=await p.evaluate(()=>JSON.parse(localStorage.getItem('spacologyBattleResult')));assert.equal(r.observation,false);assert.equal(r.gold,41);assert.equal(r.integrity,2)});
 await test('mid-voyage modifier and one paid removal are enforced',async({p,state,seed})=>{await seed({round:4,goalLocked:true,modifiers:['reinforced'],modifierChoices:[1]});await p.locator('[data-info="modifiers"]').click();await p.locator('[data-modifier="volatile"]').click();assert.deepEqual((await state()).modifiers,['reinforced','volatile']);await p.locator('[data-remove-modifier="reinforced"]').click();assert.deepEqual((await state()).modifiers,['volatile']);assert.equal((await state()).gold,34);assert.equal((await state()).modifierRemovalUsed,true);assert(await p.locator('[data-remove-modifier="volatile"]').isDisabled())});
 await test('inbox and goal payout persist once; route and completed voyage restore',async({p,state,seed})=>{await seed({round:2,goal:'survey',goalProgress:5,goalLocked:true,reserve:['Ash'],equipped:{Ash:['Bore Bit']}});await p.evaluate(()=>localStorage.setItem('spacologyBattleResult',JSON.stringify({round:2,won:true,gold:40,integrity:5,breaks:2,chains:0,deaths:0,actions:10,ultimates:2,crystals:1,item:{type:'gear',name:'Bore Bit'}})));await p.reload();assert(await p.locator('#titleScreen').isHidden());let s=await state();assert.equal(s.gold,90);assert.equal(s.crystals,2);assert.equal(s.scrap,4);assert.equal(s.inbox.length,1);assert.equal(s.goalClaimed,true);assert.equal(s.integrity,75);assert.equal(await p.locator('.round-map .complete').count(),2);await p.locator('[data-open-inbox]').click();assert.match(await p.locator('#modalBody').textContent(),/Bore Bit.*4 scrap/);assert.equal((await state()).gold,90);await p.reload();await p.locator('#enterOps').click();assert.equal((await state()).inbox.length,1);assert.equal((await state()).gold,90);await p.evaluate(()=>{let s=JSON.parse(localStorage.getItem('spacologyRunV010'));s.round=7;localStorage.setItem('spacologyRunV010',JSON.stringify(s))});await p.reload();await p.locator('#enterOps').click();assert(await p.locator('#voyageEnd').isVisible());await p.locator('#finalInbox').click();assert(await p.locator('#overlay').isVisible())});
 await test('star atlas selects real shared-rule affiliations',async({p})=>{await p.goto(base+'/prototypes/star-atlas.html');assert.equal(await p.locator('[data-world]').count(),6);await p.locator('[data-world="3"]').click();assert.match(await p.locator('#detail').textContent(),/Coda/);assert.match(await p.locator('#detail').textContent(),/Ledger/);assert.match(await p.locator('#detail').textContent(),/Lamp at Periapsis/)});
 await browser.close();if(failures.length){console.error(failures.join('\n'));process.exitCode=1}
})().catch(e=>{console.error(e);process.exitCode=1});
