const {chromium}=require('playwright');const assert=require('node:assert/strict');const base=process.env.SPACOLOGY_BASE_URL||'http://127.0.0.1:4175';
(async()=>{const b=await chromium.launch({headless:true});try{const p=await b.newPage({serviceWorkers:'block',viewport:{width:1024,height:768}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/prototypes/spacology-v0.1.0.html');await p.evaluate(()=>{const s=JSON.parse(localStorage.spacologyRunV010);Object.assign(s,{field:['Tarn','Bosk'],support:['Coda','Maul'],reserve:[],crewCopies:[],copyProgression:1,crystals:4,scrap:28});localStorage.spacologyRunV010=JSON.stringify(s)});await p.reload();await p.locator('#enterOps').click();await p.locator('[data-info="forge"]').click();await p.locator('[data-recipe="Lumen Conduit"]').click();await p.locator('[data-craft="Lumen Conduit"]').click();await p.locator('[data-craft-dynamo]').click();let s=await p.evaluate(()=>JSON.parse(localStorage.spacologyRunV010));assert.equal(s.crystals,0);assert.equal(s.scrap,0);assert(s.gear.includes('Lumen Conduit'));assert(s.shipInventory.includes('Prismatic Dynamo'));await p.locator('#closeModal').click();await p.evaluate(()=>{const s=JSON.parse(localStorage.spacologyRunV010);s.equipped={Tarn:['Lumen Conduit']};s.gear=[];s.shipEquipped=['Prismatic Dynamo'];s.shipInventory=[];localStorage.spacologyRunV010=JSON.stringify(s)});await p.reload();await p.locator('#enterOps').click();
let totalGold=s.gold;
for(let round=1;round<=6;round++){
 await p.locator('#continueButton').click();await p.waitForURL('**/watchable-fight.html**');
 const result=await p.evaluate(()=>{cancelSessionAutostart();playing=false;MODE='none';if(G.actions!==0)throw Error('Autostart ran before test');const energy=G.units.find(u=>u.n==='Tarn').en,ult=G.units.find(u=>u.n==='Tarn').ultMul;for(let step=0;step<3000;step++){const ev=resolveAction();if(ev.end){finish(ev.end);return {energy,ult,result:JSON.parse(localStorage.spacologyBattleResult)}}G.actions++;sweepFoes();}throw Error('Battle did not finish')});
 assert.equal(result.energy,65);assert.equal(result.ult,1.2);if(result.result.won)assert(result.result.crystals>=1);totalGold+=result.result.gold;
 await p.locator('#summaryReturn').click();await p.waitForURL('**/spacology-v0.1.0.html?return=1');assert(await p.locator('#titleScreen').isHidden());s=await p.evaluate(()=>JSON.parse(localStorage.spacologyRunV010));assert.equal(s.round,round+1);assert.equal(s.inbox.length,round);assert(s.gold>=totalGold);await p.reload();assert(await p.locator('#titleScreen').isHidden());const again=await p.evaluate(()=>JSON.parse(localStorage.spacologyRunV010));assert.equal(again.gold,s.gold);assert.equal(again.inbox.length,round);
}
assert(await p.locator('#voyageEnd').isVisible());assert.deepEqual(errors,[]);console.log('PASS crystal-crafted gear and ship effects work in all six real encounters; each returns directly to Ops, pays once and reaches voyage summary');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
