#!/usr/bin/env python3
"""Turns sweep.json into balance-workbook.xlsx plus one CSV per sheet.

    node sweep.js  &&  python3 build-workbook.py

CSVs are written alongside because this sandbox has no working spreadsheet
application to validate the xlsx against, and a CSV opens anywhere.
"""

import csv
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from xlsxwrite import Workbook  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "sweep.json")
XLSX = os.path.join(HERE, "balance-workbook.xlsx")
CSVDIR = os.path.join(HERE, "workbook-csv")

if not os.path.exists(SRC):
    sys.exit("sweep.json not found — run `node sweep.js` first")

D = json.load(open(SRC))
M = D["meta"]
wb = Workbook()
os.makedirs(CSVDIR, exist_ok=True)
sheets = []


def add(name, header, rows, widths=None, formats=None):
    """Add a sheet to the workbook and write the same data as a CSV."""
    wb.sheet(name, header, rows, widths=widths, formats=formats)
    path = os.path.join(CSVDIR, name.lower().replace(" ", "-") + ".csv")
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(header)
        w.writerows(rows)
    sheets.append((name, len(rows)))


# --------------------------------------------------------------- Readme ----
readme = [
    ["Generated by", M["generated"] + "  then  python3 build-workbook.py"],
    ["Teams sampled", M["sample"]],
    ["Characters per team", M["teamSize"]],
    ["Fights per difficulty probe", M["fightsPerProbe"]],
    ["Difficulty ceiling", M["ceiling"]],
    ["Binary search steps", M["searchSteps"]],
    ["Baseline (mean team score)", M["baseline"]],
    ["Worlds", ", ".join(M["worlds"])],
    ["", ""],
    ["WHAT A SCORE MEANS", ""],
    ["bp", "Breakpoint: the difficulty multiplier at which the team still wins 3 fights in 4."],
    ["", "Higher is stronger. Scored by breakpoint rather than win rate because win rate"],
    ["", "saturates and stops discriminating once a team is comfortably ahead."],
    ["", ""],
    ["WHY THE CEILING MATTERS", ""],
    ["", "scoreTeam searches difficulty over a range. With the old default of 6.0 the highest"],
    ["", "value it could return was 5.96, which means 'beat the hardest difficulty tried' and"],
    ["", "not a breakpoint. Strong teams landed there on two worlds of five, flattening the"],
    ["", "top of every ranking. Everything here uses a ceiling of %s." % M["ceiling"]],
    ["", ""],
    ["WHAT THIS CANNOT TELL YOU", ""],
    ["", M["caveat"]],
    ["", ""],
    ["DEFAULT TUNING", ""],
] + [[k, v] for k, v in M["defaults"].items()] + [
    ["", ""],
    ["TABS", ""],
    ["Roster", "Every character: roles, stats, which verbs it carries, what it depends on"],
    ["Verbs", "How many characters carry each verb. A verb on one character gives every"],
    ["", "chain through it exactly one possible shape"],
    ["Teams", "Sampled teams scored on every world. Sort by avg, or by swing to find the"],
    ["", "most world-dependent builds"],
    ["Characters", "How much banning each character costs the ceiling — the mandatory-unit test"],
    ["Role lift", "Mean team score when N of a role are present, against baseline"],
    ["Elements", "Whether doubling up on an element pays, and how often Harmony fires"],
    ["Worlds", "Which worlds discriminate between teams and which only measure competence"],
    ["Sensitivity", "One combat constant varied at a time, everything else at default"],
    ["Sensitivity summary", "Which constants actually move the game. Start here"],
]
add("Readme", ["field", "value"], readme, widths=[30, 96])

# --------------------------------------------------------------- Roster ----
add("Roster",
    ["character", "roles", "dmg", "speed", "hpMul", "hooks", "verbs", "procs on",
     "proc dmg", "max procs", "depends on", "bio"],
    [[r["name"], r["roles"], r["dmg"], r["speed"], r["hpMul"], r["hooks"], r["verbs"],
      r["procOn"], r["procDmg"], r["procMax"], r["needs"], r["bio"]] for r in D["roster"]],
    widths=[11, 18, 6, 6, 7, 7, 34, 9, 7, 7, 26, 62],
    formats=[None, None, "int", "int", "2dp", "int", None, None, "2dp", "int", None, None])

# ---------------------------------------------------------------- Verbs ----
add("Verbs", ["verb", "characters", "holders"],
    [[v["verb"], v["count"], v["holders"]] for v in D["verbs"]],
    widths=[16, 12, 60], formats=[None, "int", None])

# ---------------------------------------------------------------- Teams ----
W = M["worlds"]
add("Teams",
    ["team"] + W + ["avg", "best", "worst", "swing", "hooks", "roles at 2+", "deep role",
     "elements", "duplicate elements", "harmonies"],
    [[t["team"]] + [t[w] for w in W] +
     [t["avg"], t["best"], t["worst"], t["swing"], t["hooks"], t["rolesAt2"], t["deepRole"],
      t["elements"], t["sharedElements"], t["harmonies"]]
     for t in D["teams"]],
    widths=[40] + [9] * len(W) + [8, 8, 8, 8, 7, 26, 14, 34, 19, 11],
    formats=[None] + ["2dp"] * len(W) + ["2dp", "2dp", "2dp", "2dp", "int", None, None,
                                          None, "int", "1dp"])

# ----------------------------------------------------------- Characters ----
add("Characters",
    ["character", "roles", "hooks", "in top 50", "share of top teams", "share of slots",
     "best team without", "cost of banning", "depends on"],
    [[c["name"], c["roles"], c["hooks"], c["topFreq"], c["topShare"], c["slotShare"],
      c["bestWithout"], c["costOfBanning"], c["needs"]] for c in D["characters"]],
    widths=[11, 18, 7, 11, 19, 15, 18, 16, 26],
    formats=[None, None, "int", "int", "pct", "pct", "2dp", "pct", None])

# -------------------------------------------------------------- Tag lift ----
add("Role lift", ["role", "count", "teams", "mean score", "vs baseline", "at 2", "at 4"],
    [[t["tag"], t["count"], t["n"], t["mean"], t["vsBaseline"], t["at2"], t["at4"]]
     for t in D["roles"]],
    widths=[12, 8, 8, 12, 13, 40, 62],
    formats=[None, "int", "int", "2dp", "pct", None, None])

# --------------------------------------------------------------- Worlds ----
add("Worlds",
    ["world", "note", "speedMul", "min", "median", "max", "spread x", "censored at 6.0", "mix"],
    [[w["world"], w["note"], w["speedMul"], w["min"], w["median"], w["max"], w["spread"],
      w["wouldBeCensoredAt6"], w["mix"]] for w in D["worlds"]],
    widths=[11, 42, 10, 8, 9, 8, 10, 16, 30],
    formats=[None, None, "2dp", "2dp", "2dp", "2dp", "2dp", "int", None])

# ------------------------------------------------------------- Elements ----
add("Elements",
    ["duplicate elements", "teams", "mean score", "vs baseline", "harmonies per fight", "best"],
    [[e["sharedElements"], e["teams"], e["meanScore"], e["vsBaseline"], e["meanHarmonies"],
      e["best"]] for e in D.get("elements", [])],
    widths=[19, 8, 12, 13, 21, 8],
    formats=["int", "int", "2dp", "pct", "1dp", "2dp"])

# ---------------------------------------------------------- Sensitivity ----
add("Sensitivity", ["constant", "value", "is default", "team", "world", "bp"],
    [[s["constant"], s["value"], "yes" if s["isDefault"] else "", s["team"], s["world"], s["bp"]]
     for s in D["sweep"]],
    widths=[11, 9, 11, 34, 10, 8],
    formats=[None, "2dp", None, None, None, "2dp"])

# -------------------------------------------------- Sensitivity summary ----
# For each constant and value, the mean across probe teams and worlds, then how
# far the constant moves the game across its whole tested range.
by = {}
for s in D["sweep"]:
    by.setdefault((s["constant"], s["value"]), []).append(s["bp"])

summary, spans = [], {}
for (const_, val), vals in sorted(by.items()):
    mean = sum(vals) / len(vals)
    spans.setdefault(const_, []).append(mean)
    is_def = any(s["isDefault"] for s in D["sweep"]
                 if s["constant"] == const_ and s["value"] == val)
    summary.append([const_, val, "yes" if is_def else "", len(vals), round(mean, 3)])

# append a swing column: how much this constant moves the mean, relative to its own span
rows = []
for r in summary:
    m = spans[r[0]]
    swing = (max(m) - min(m)) / max(0.01, min(m))
    rows.append(r + [round(swing, 3)])
rows.sort(key=lambda r: (-r[5], r[0], r[1]))

add("Sensitivity summary",
    ["constant", "value", "is default", "samples", "mean bp", "range of this constant"],
    rows, widths=[11, 9, 11, 10, 11, 23],
    formats=[None, "2dp", None, "int", "2dp", "pct"])

wb.save(XLSX)
print(f"wrote {XLSX}")
for name, n in sheets:
    print(f"  {name:22s} {n:5d} rows")
print(f"csv copies in {CSVDIR}/")
