(function () {
  'use strict';
  const crew = {
    Ilka:{element:'order',tags:['Hull','Crew'],planet:'Verekh III',species:'Deer-horned human',birthplace:'Verekh III orbital shipyards',position:'field',stats:{hp:126,dmg:10,speed:10},portrait:'../assets/cast/ilka-voressen-v2.png',role:'Fixed barrier engineer',summary:'Builds the same dependable barrier every time.',kit:{basic:['Tapline','Deals damage and grants a small fixed barrier.'],skill:['Load Standard','Grants the whole crew a large fixed barrier.'],passive:['Preventive Maintenance','The first ally struck each cycle gains emergency plating.'],plan:'Use Ilka when the team needs predictable protection rather than burst recovery.'}},
    Reva:{element:'chaos',tags:['Hull','Ordnance'],planet:'Belune III',species:'Human',birthplace:'Belune III',position:'field',stats:{hp:102,dmg:14,speed:11},portrait:'../assets/cast/reva-sokolovna-v2.png',role:'Volatile interception',summary:'Draws attacks into an irreplaceable display shell.',kit:{basic:['Shell Rush','Strikes and sharply raises her target priority.'],skill:['Last Display','Taunts all enemies; returned damage varies with what the shell endured.'],passive:['All or Nothing','Her barrier holds completely, then shatters into retaliation.'],plan:'Pair Reva with reliable shielding so her chaotic retaliation has time to peak.'}},
    'Tomás':{element:'growth',tags:['Hull','Ordnance'],planet:'Orrowan V',species:'Fungal person',birthplace:'Orrowan V',position:'both',stats:{hp:118,dmg:13,speed:8},portrait:'../assets/cast/tomas-iriarte-v5.png',role:'Escalating biotic fortification',summary:'Grafts living protection that thickens while unbroken.',kit:{basic:['Sap Graft','Damages an enemy and grows bark over the weakest ally.'],skill:['Close the Gallery','Builds a team barrier that strengthens each cycle.'],passive:['Still Growing','His oldest surviving barrier gains strength after every action.'],plan:'Protect Tomás early; his structures become exceptional in longer encounters.'}},
    Ojo:{element:'growth',tags:['Hull'],planet:'Tannhul VI',species:'Rock-and-plant humanoid',birthplace:'Tannhul VI',position:'field',stats:{hp:154,dmg:13,speed:6},portrait:'../assets/lore/ojo-mbeki-v1.webp',role:'Sustained containment tank',summary:'Absorbs pressure and becomes harder to move each cycle.',kit:{basic:['Set Weight','Deals damage and increases Ojo’s containment.'],skill:['Nothing Leaves','Taunts all enemies and converts a share of damage into recovery.'],passive:['Rooted Mass','Maximum health and resistance rise while Ojo remains on field.'],plan:'Let Ojo occupy the front through long fights while faster allies work around him.'}},
    Stella:{element:'decay',tags:['Blight','Assay'],planet:'Utora VII',species:'Oni',birthplace:'Utora VII',position:'both',stats:{hp:96,dmg:18,speed:10},portrait:'../assets/cast/stella-anuye-v2.png',role:'Front-loaded reagent specialist',summary:'Aerosolizes samples into permanent corrosion.',kit:{basic:['Reagent Mist','Hits all enemies, applies Fracture and consumes one existing stack.'],skill:['Irreversible Assay','Applies heavy permanent decay and shield damage to all enemies.'],passive:['Instrumented Method','The first new enemy type scanned each fight takes increased damage from Blight.'],plan:'Stella is self-sufficient AoE Blight that also amplifies other Blight users.'}},
    Nour:{element:'chaos',tags:['Blight','Ordnance'],planet:'Sindal II',species:'Mana-born',birthplace:'Sindal II',position:'both',stats:{hp:90,dmg:20,speed:10},portrait:'../assets/cast/nour-bediako-v3.png',role:'Unstable burn attacker',summary:'Commits completely, leaving volatile damage behind.',kit:{basic:['Bloom Reach','Deals variable damage and applies three volatile stacks.'],skill:['Cut the Root','Detonates Nour’s stacks for a high but unstable multiplier.'],passive:['Still Burning','Targets touched by Nour keep one stack after a detonation.'],plan:'Nour can seed and spend alone; other blight crew make the detonation much larger.'}},
    Dolores:{element:'chaos',tags:['Blight'],planet:'Calyx IV',species:'Fungal people',birthplace:'Calyx IV',position:'both',stats:{hp:104,dmg:16,speed:9},portrait:'../assets/cast/dolores-achterberg-v7.png',role:'Breach detonator',summary:'A warm senior researcher and mother who opens routes through accumulated corruption.',kit:{basic:['Hyphal Charge','Applies one blight stack and primes the target.'],skill:['Breach and Bloom','Detonates every stack on a selected target and splashes adjacent enemies.'],passive:['Enough to Open','Her detonations trigger at a lower stack threshold.'],plan:'Dolores works alone, but rewards teams that build large condition piles quickly.'}},
    Spore:{fullName:'Mary Achterberg',element:'growth',tags:['Blight','Crew'],planet:'Calyx IV',species:'Fungal people',birthplace:'Calyx IV',position:'support',stats:{hp:98,dmg:12,speed:10},portrait:'../assets/cast/spore-v2.png',role:'Network spread and recovery',summary:'Dolores’s young-adult daughter spreads conditions through a living fungal map.',kit:{basic:['Culture Thread','Applies a stack and heals the most injured ally.'],skill:['Bloomtide','Spreads every target’s oldest condition and grants a team barrier.'],passive:['Daughter Network','The first condition consumed each cycle regrows on an adjacent target.'],plan:'Use Spore behind a front line that needs time for conditions and recovery to spread.'}},
    Abike:{element:'growth',tags:['Blight','Crew'],planet:'Ombrea II',species:'Avian humanoid',birthplace:'Ombrea II',position:'support',stats:{hp:101,dmg:11,speed:10},portrait:'../assets/cast/abike-sunmonu-v2.png',role:'Decomposition healer',summary:'Turns defeated corruption into material for recovery.',kit:{basic:['Rot Culture','Applies blight and restores a small amount of health.'],skill:['Generous Decay','Consumes conditions across all enemies to heal and overheal the crew.'],passive:['Nothing Wasted','When an enemy falls, one condition jumps and the weakest ally recovers.'],plan:'Abike converts condition-heavy encounters into durable team sustain.'}},
    Aurel:{element:'energy',tags:['Drive','Crew'],planet:'Tessine IX',species:'Moth-folk',birthplace:'Tessine IX',position:'support',stats:{hp:88,dmg:14,speed:13},portrait:'../assets/cast/aurel-cosma-v2.png',role:'Immediate tempo navigator',summary:'Reads an opening and moves an ally into it early.',kit:{basic:['Lane Call','Deals damage and advances the next ally.'],skill:['Full Ahead','Immediately advances the entire crew and restores a little health.'],passive:['Correct Direction','The first ally to act after Aurel gains bonus damage.'],plan:'Aurel compresses setup time for slower formations and teams that rely on ultimates.'}},
    Imke:{element:'energy',tags:['Drive','Ordnance'],planet:'Ilex Moraine',species:'Fox-descended human',birthplace:'Ilex Moraine',position:'both',stats:{hp:86,dmg:14,speed:14},portrait:'../assets/cast/imke-v3.png',role:'Reactive fox skirmisher',summary:'Fires whenever somebody else creates an opening.',kit:{basic:['Nettle Shot','Fast direct attack that slightly advances Imke.'],skill:['Couldn’t Wait','Acts immediately and repeats the last allied target.'],passive:['Too Eager','Answers a limited number of allied attacks with a light follow-up.'],plan:'Frequent allied actions turn Imke into a fast stream of secondary damage.'}},
    Idris:{element:'energy',tags:['Drive','Assay'],planet:'Verekh III',species:'Mana-born feline',birthplace:'Verekh III',position:'support',stats:{hp:87,dmg:13,speed:13},portrait:'../assets/cast/idris-okonjo-v2.png',role:'Remote swarm surveyor',summary:'Sweeps the entire line with instrument motes.',kit:{basic:['Mote Sweep','Light AoE damage and shield damage.'],skill:['Thirty-One Lights','Deploys a swarm that repeatedly scans every enemy.'],passive:['Remote Read','Scanned targets take increased shield damage from the next ally.'],plan:'Idris combines tempo and broad break setup from the safety of support.'}},
    Beatriz:{element:'void',tags:['Ordnance'],planet:'Utora VII',species:'Human',birthplace:'Utora VII',position:'field',stats:{hp:112,dmg:25,speed:7},portrait:'../assets/cast/beatriz-corriveau-v2.png',role:'Single-target hazard response',summary:'Removes one dangerous problem with one exact shot.',kit:{basic:['One Number','High damage against one selected enemy.'],skill:['Event Horizon','Erases one shield layer and delivers an extreme void strike.'],passive:['No Second Target','Damage rises while Beatriz keeps attacking the same enemy.'],plan:'Use marks and break effects to focus Beatriz on the encounter’s priority target.'}},
    Otaremnivas:{element:'decay',tags:['Hull','Crew'],planet:'Ranohe IV',species:'Stone-bodied humanoid',birthplace:'Ranohe IV',position:'field',stats:{hp:140,dmg:12,speed:6},portrait:'../assets/cast/otaremnivas-v2.png',role:'Containment specialist',summary:'Contains dangerous bodies without treating them as disposable.',kit:{basic:['Gentle Restraint','Deals damage and lowers the target’s attack.'],skill:['Whole Weight','Pins all enemies and shields the weakest allies.'],passive:['Handler’s Patience','Contained targets deal less damage each cycle they remain controlled.'],plan:'Otaremnivas trades speed for broad containment and protection.'}},
    Wren:{element:'decay',tags:['Hull','Assay'],planet:'Tannhul VI',species:'Human',birthplace:'Tannhul VI',position:'both',stats:{hp:122,dmg:15,speed:8},portrait:'../assets/cast/wren-adeyemi-v2.png',role:'Structural fracture analyst',summary:'Finds the load path and makes one crack permanent.',kit:{basic:['Stress Read','Deals shield damage and marks a structural seam.'],skill:['Fault Line','Breaks marked shields and grants plating from the debris.'],passive:['Remembered Fracture','A repaired shield layer returns weaker than before.'],plan:'Wren supplies durable break pressure without depending on another marker.'}},
    Nadira:{element:'void',tags:['Blight','Assay'],planet:'Sindal II',species:'Canid',birthplace:'Sindal II',position:'support',stats:{hp:89,dmg:13,speed:12},portrait:'../assets/cast/nadira-quill-v2.png',role:'Xenobotanical negation',summary:'Identifies which living process should be stopped rather than harmed.',kit:{basic:['Quiet Sample','Applies a mark and a void condition to one enemy.'],skill:['Stop the Process','Suspends marked actions and consumes conditions for shield damage.'],passive:['Eleven Objections','The first permanent condition applied each cycle is amplified.'],plan:'Nadira controls dangerous actions while supporting both blight and assay teams.'}},
    Yusuf:{element:'void',tags:['Assay','Drive'],planet:'Belune III',species:'Prismborn',birthplace:'Belune III crystal reefs',position:'both',stats:{hp:91,dmg:12,speed:12},portrait:'../assets/cast/yusuf-benhaddou-v3.png',role:'Wide reef survey',summary:'Reads refraction through living crystal and paints the whole enemy line with a fast scan.',kit:{basic:['Survey Pass','Light AoE damage and one mark on every enemy.'],skill:['Complete Transect','Heavy shield-damage sweep that advances marked allies.'],passive:['One Flight','The first AoE action each cycle costs less time.'],plan:'Yusuf supplies broad marks and tempo for teams that dislike single-target setup.'}},
    Sevim:{element:'order',tags:['Assay'],planet:'Belune III',species:'Human',birthplace:'Belune III',position:'support',stats:{hp:94,dmg:13,speed:10},portrait:'../assets/cast/sevim-aydar-v2.png',role:'Exact materials assay',summary:'Applies slow, identical pressure until a shell opens itself.',kit:{basic:['Measured Cooling','Fixed shield damage and a persistent stress mark.'],skill:['Four-Hour Seam','Breaks every fully stressed shield layer at once.'],passive:['Patience','Stress never decays and each application is identical.'],plan:'Sevim is slow, exact break setup that rewards deliberate formations.'}},
    Aurelio:{element:'order',tags:['Assay','Drive'],planet:'Tessine IX',species:'Tortoise-descended humanoid',birthplace:'Census ship',position:'both',stats:{hp:90,dmg:15,speed:11},portrait:'../assets/cast/aurelio-bassi-v3.png',role:'Catalogue mark responder',summary:'A shell-backed quartermaster who answers every properly recorded opening.',kit:{basic:['Archive Shot','Deals damage and adds one catalogue mark.'],skill:['Final Entry','Strikes every marked enemy and advances the next ally.'],passive:['According to Record','Answers the first new mark each cycle with a follow-up.'],plan:'Aurelio marks and responds alone; other surveyors increase his answer rate.'}},
    Nahana:{element:'order',tags:['Crew'],planet:'Maelus IV',species:'Aquatic humanoid',birthplace:'Maelus IV',position:'support',stats:{hp:103,dmg:9,speed:11},portrait:'../assets/cast/nahana-v2.png',role:'Reliable faunal care',summary:'Provides the same competent recovery every cycle.',kit:{basic:['Keeper’s Hand','Light damage and fixed healing to the weakest ally.'],skill:['Nobody Left','Restores the whole crew by a fixed amount.'],passive:['Steady Care','The most injured ally receives a small heal after each enemy cycle.'],plan:'Nahana supplies consistent healing without timing requirements or variance.'}},
    Navigator:{element:'growth',tags:['Crew','Hull'],planet:'Iseul III',species:'Constructed humanoid',birthplace:'Iseul III',position:'both',stats:{hp:110,dmg:10,speed:9},portrait:'../assets/cast/navigator-v2.png',role:'Escalating voyage support',summary:'Their song becomes stronger the longer an encounter lasts.',kit:{basic:['Hold the Song','Damages an enemy and grows a small overheal barrier.'],skill:['Lane Remains','Heals the team; the amount rises each cycle.'],passive:['Four Lost Songs','All Navigator effects grow while the encounter continues.'],plan:'Navigator is weak in short fights and exceptional in prolonged recovery work.'}},
    Ekene:{element:'energy',tags:['Crew','Drive'],planet:'Orrowan V',species:'Mana-born',birthplace:'Orrowan V',position:'support',stats:{hp:84,dmg:11,speed:12},portrait:'../assets/lore/ekene-baptiste-v2.png',role:'Ultimate charge support',summary:'A mana-born engineer who gives away her stored charge in one bright burst.',kit:{basic:['Distribution Pulse','Deals damage and grants ultimate charge to the next ally.'],skill:['Empty the Bloom','Fully charges allies and heavily advances them, then slows Ekene.'],passive:['Runs Cold','The first ultimate charge spent each cycle lightly heals its user.'],plan:'Ekene enables ultimate-heavy teams but needs protection during her recovery.'}},
    Bosk:{element:'decay',tags:['Ordnance','Hull'],planet:'Ilex Moraine',species:'Human-forward ursine',birthplace:'Good Weather recovery arc',position:'field',stats:{hp:124,dmg:20,speed:6},portrait:'../assets/cast/bosk-v4.png',role:'Heavy recovery striker',summary:'Applies patient weight to the weakest structural point.',kit:{basic:['Falling Cargo','Slow heavy damage that weakens restored shields.'],skill:['Bring It Home','Massive strike that converts overkill into team plating.'],passive:['Salvage Respect','Breaking a shield grants Bosk a permanent damage bonus.'],plan:'Give Bosk tempo support and let her turn breaks into durable pressure.'}},
    Coda:{element:'energy',tags:['Drive','Crew'],planet:'Tessine IX',species:'Moth-folk',birthplace:'Lamp at Periapsis relay',position:'support',stats:{hp:86,dmg:14,speed:13},portrait:'../assets/cast/coda-v2.png',role:'Answering-note support',summary:'Completes the action another crewmate begins.',kit:{basic:['Echo Note','Damages the last allied target and grants ultimate charge.'],skill:['Coda','Repeats the last allied support effect at reduced strength.'],passive:['Answering Harmonic','The first follow-up each cycle advances its owner.'],plan:'Coda magnifies active formations with frequent, varied actions.'}},
    Morrow:{element:'growth',tags:['Blight'],planet:'Ilex Moraine',species:'Cervine',birthplace:'Ilex Moraine',position:'both',stats:{hp:94,dmg:14,speed:9},portrait:'../assets/cast/morrow-v2.png',role:'Succession condition specialist',summary:'Plants what will grow after the damage passes.',kit:{basic:['First Film','Applies two growth stacks and consumes one for damage.'],skill:['What Grows Next','Escalates every condition, then seeds a replacement after detonation.'],passive:['Second Beginning','A cleansed target retains one beneficial vulnerability.'],plan:'Morrow creates persistent condition value even against cleansing enemies.'}},
    Maul:{element:'decay',tags:['Assay','Ordnance'],planet:'Earth',species:'Human',birthplace:'Kessa Station',position:'support',stats:{hp:116,dmg:20,speed:7},portrait:'../assets/cast/maul-v2.png',role:'Break responder',summary:'Waits for a fracture and puts everything into it.',kit:{basic:['Test Blow','Deals damage and modest shield damage.'],skill:['Deadweight','Extreme damage to a broken or marked enemy.'],passive:['Into the Gap','Answers the first enemy break with a heavy follow-up.'],plan:'Maul can help make a crack himself, but dedicated assay allies unlock his full force.'}},
    Quill:{element:'void',tags:['Blight','Assay'],planet:'Earth',species:'Human',birthplace:'Iseul orbital diaspora',position:'support',stats:{hp:88,dmg:15,speed:12},portrait:'../assets/cast/quill-v2.png',role:'Remote enemy marker',summary:'Makes hidden boundaries visible to the entire team.',kit:{basic:['Mark Enemy','Attacks and applies three marks.'],skill:['Full Survey','Marks and damages all enemies.'],passive:['Moving Model','Quill follows the first consumed mark each cycle with a void shot.'],plan:'Quill supplies precise shared targets for breakers and focused attackers.'}},
    Tarn:{element:'order',tags:['Hull','Ordnance'],planet:'Earth',species:'Human',birthplace:'Tannhul VI diaspora',position:'field',stats:{hp:136,dmg:12,speed:7},portrait:'../assets/cast/tarn-v2.png',role:'Expedition route anchor',summary:'Names a position and makes it remain safe.',kit:{basic:['Anchor Strike','Deals damage and grants Tarn fixed plating.'],skill:['Promised Position','Taunts all enemies and shields every ally behind her.'],passive:['Still Here','The first hit against Tarn each cycle returns fixed damage.'],plan:'Tarn anchors fragile support crews with simple, reliable protection.'}},
    Redcap:{fullName:'Liora Venn',element:'growth',tags:['Assay','Crew'],planet:'Calyx IV',species:'Fungal people',birthplace:'Calyx IV university annex',position:'support',stats:{hp:106,dmg:10,speed:9},portrait:'../assets/cast/redcap-v1.png',role:'Culture stabilization researcher',summary:'A cheerful field mycologist who keeps fragile cultures—and crewmates—alive.',kit:{basic:['Culture Check','Marks one enemy and restores the weakest ally.'],skill:['Keep It Growing','Preserves allied barriers and conditions, then grants gradual recovery.'],passive:['Living Sample','The first condition that would expire each cycle is refreshed once.'],plan:'Redcap supports long experiments by preserving the crew’s setup instead of rushing it.'}},
    Hanae:{element:'energy',tags:['Assay','Drive'],planet:'Tannhul VI',species:'Porcelain stoneskin',birthplace:'Tannhul VI resonance terraces',position:'both',stats:{hp:108,dmg:14,speed:10},portrait:'../assets/cast/hanae-mori-v3.png',role:'Resonance opening specialist',summary:'Her repaired mineral seams sing when she finds the frequency hidden inside a shell.',kit:{basic:['Sounding Knock','Deals shield damage and records the target’s resonance.'],skill:['Sing It Back','Strikes every recorded target and advances the next ally.'],passive:['Golden Echo','The first Break each cycle lights her repairs and grants the crew ultimate charge.'],plan:'Hanae turns careful assay work into fast, team-wide momentum.'}},
    Arunima:{element:'void',tags:['Assay','Crew'],planet:'Iseul III',species:'Rift-elf',birthplace:'Iseul III folded-orbit archive',position:'support',stats:{hp:92,dmg:11,speed:8},portrait:'../assets/cast/arunima-das-v4.png',role:'Topological encounter control',summary:'A four-armed cartographer who treats local space as something that can be folded by hand.',kit:{basic:['Fold a Corner','Marks one enemy and delays its next action.'],skill:['Proof by Transit','Reorders marked enemies, damages their shields and shields the crew.'],passive:['Missing Step','The first delayed enemy each cycle leaves behind a protective route.'],plan:'Arunima rewards deliberate control teams with safer turns and stronger positioning.'}},
    Atsa:{element:'growth',tags:['Hull','Assay'],planet:'Earth',species:'Human',birthplace:'Earth, Diné diaspora community',position:'both',stats:{hp:119,dmg:12,speed:9},portrait:'../assets/cast/atsa-begay-v1.png',role:'Living-route anchor',summary:'Reads a landscape as a relationship, then gives the crew firm ground.',kit:{basic:['Root Sensor','Damages and marks an enemy while granting Atsa light plating.'],skill:['Ground Truth','Raises a team barrier and exposes every marked structural seam.'],passive:['Known Way Home','The first broken shield each cycle restores the weakest barrier.'],plan:'Atsa links assay and hull crews by turning good field reads into durable protection.'}},
    'The Mage':{element:'order',tags:['Assay','Drive'],planet:'Earth',species:'Feline cyborg',birthplace:'Earth orbital diaspora',position:'support',stats:{hp:94,dmg:12,speed:11},portrait:'../assets/cast/the-mage-v1.png',role:'Persistent robot summoner',summary:'A hidden systems architect who gradually calls an eccentric three-machine support team into the field.',combat:{p:'tactician',marks:1},kit:{basic:['Constellation Ping','Deals light shield damage and scans the target.'],skill:['J3K Lottery','Summons one random missing J3K unit. Each remains in the support field until all three are active; later casts command the waiting unit forward.'],passive:['Maker’s Favor','The first J3K unit deployed each encounter acts immediately.'],plan:'Build the full J3K support line over several turns: 017 protects routes, 036 surveys all enemies and 095 handles recovery.'}}
  };
  const summons={
    'J3K-017':{form:'Manta survey unit',portrait:'../assets/cast/j3k-017-v2.png',role:'Route protection',effect:'Sweeps the field, advancing the waiting crewmate and raising a brief crew barrier.',combat:{element:'energy',hp:72,dmg:7,speed:12}},
    'J3K-036':{form:'Narwhal song-map unit',portrait:'../assets/cast/j3k-036-v7.png',role:'Harmonic survey',effect:'Maps the enemy line with resonant marks and shield damage.',combat:{element:'order',hp:78,dmg:8,speed:10}},
    'J3K-095':{form:'Penguin specimen unit',portrait:'../assets/cast/j3k-095-v2.png',role:'Sample recovery',effect:'Returns a protected sample, restoring and shielding the most injured crewmate.',combat:{element:'growth',hp:84,dmg:6,speed:9}}
  };
  const worlds=[
    {star:'Sol',name:'Earth',x:17,y:57,peoples:'Human lineages; many migrant communities.',landscape:'Oceans, continents and an old diaspora.',status:'Existing world; shared human ancestry proposed for the homeworld bonus.'},
    {star:'Calyx',name:'Calyx IV',x:43,y:71,peoples:'Fungal peoples, oni and human communities.',landscape:'Temperate forests, dense fungal ecologies and long-established mixed settlements.',status:'Existing world. Fungal/oni shared ancestral affiliation is proposed.'},
    {star:'Ilex',name:'Ilex Moraine',x:24,y:22,peoples:'Cervine, ursine and canid lineages.',landscape:'Glacial basins, conifer forests and seasonal migration corridors.',status:'Morrow’s existing world; star, ecology and shared lineages proposed.'},
    {star:'Tessine',name:'Tessine IX',x:69,y:27,peoples:'Moth-folk; mixed orbital and surface communities.',landscape:'Twilight forests and low-gravity orbital universities.',status:'Existing moth-folk world; ecology and shipborn affiliations proposed.'},
    {star:'Tannhul',name:'Tannhul VI',x:78,y:74,peoples:'Rock skins and human diaspora communities.',landscape:'High-gravity cities and load-bearing reef settlements.',status:'Existing high-gravity world; does not replace Earth ancestry for Tarn.'},
    {star:'Iseul',name:'Iseul III',x:52,y:43,peoples:'Ossuan and human orbital communities.',landscape:'Survey networks linking planetary and orbital settlements.',status:'Existing world; birthplace and ancestral affiliation are distinct.'}
  ];
  const shipParts={
    'Fast Clock':{effect:'All crew begin battle 8 Action Value ahead.',startAdvance:8,upgrade:'Fast Clock II'},
    'Fast Clock II':{effect:'All crew begin battle 16 Action Value ahead.',startAdvance:16},
    'Exact Clock':{effect:'All crew begin battle with 20 ultimate charge.',startEnergy:20,upgrade:'Exact Clock II'},
    'Exact Clock II':{effect:'All crew begin battle with 35 ultimate charge.',startEnergy:35},
    'Prismatic Dynamo':{effect:'All crew begin battle with 30 extra ultimate charge.',startEnergy:30,upgrade:'Prismatic Dynamo II'},
    'Prismatic Dynamo II':{effect:'All crew begin battle with 45 extra ultimate charge.',startEnergy:45},
    'Culture Bed':{effect:'Fracture applications add 1 extra stack.',stacks:1,upgrade:'Culture Bed II'},
    'Culture Bed II':{effect:'Fracture applications add 2 extra stacks.',stacks:2},
    'Brace Matrix':{effect:'Reduces the first incoming hit each battle by 40%.',brace:1,upgrade:'Brace Matrix II'},
    'Brace Matrix II':{effect:'Reduces the first 2 incoming hits each battle by 40%.',brace:2},
    'Survey Prism':{effect:'Completed observations award 20% more gold.',survey:.2,upgrade:'Survey Prism II'},
    'Survey Prism II':{effect:'Completed observations award 35% more gold.',survey:.35}
  };
  const recipes = [
    {name:'Lumen Conduit',inputs:[],scrap:12,crystals:2,effect:'Begin battle with 35 extra ultimate charge; ultimate damage increases by 20%.',stats:{startEnergy:35,ultMul:1.2}},
    {name:'Resonance Coil', inputs:['Tuning Fork','Spore Sling'], effect:'Applications add 1 stack; spread reaches 1 additional enemy.', stats:{frac:1,spreadExtra:1}},
    {name:'Survey Lance', inputs:['Ranging Sight','Bore Bit'], effect:'Attacks also hit 1 other enemy and deal 40% more shield damage.', stats:{extraTargets:1,guardMul:1.4}},
    {name:'Counterweight', inputs:['Loaded Die','Recoil Spring'], effect:'First attack deals 20% more damage; follow-ups deal 30% more.', stats:{openingBoost:.2,followMul:1.3}},
    {name:'Overdrive Relay', inputs:['Quick Latch','Slow Fuse'], effect:'Start 8 Action Value ahead; ultimates deal 25% more damage.', stats:{startAdvance:8,ultMul:1.25}},
    {name:'Breach Mantle', inputs:['Ballast Plate','Bore Bit'], effect:'Barriers are 45% larger; attacks deal 60% more shield damage.', stats:{barrierMul:1.45,guardMul:1.6}}
  ];
  const modifiers = {
    reinforced:{name:'Reinforced enemies',category:'stat',description:'Enemies have 25% more health. Victory gold increases by 20%.',enemyHp:1.25,reward:1.2},
    volatile:{name:'Volatile atmosphere',category:'rule',description:'Crew and enemies deal 20% more direct attack damage.',crewDamage:1.2,enemyDamage:1.2},
    rationing:{name:'Salvage contract',category:'cost',description:'Supply packs cost 2 more gold. Each completed encounter pays 6 extra gold.',packCost:2,flatGold:6}
  };
  const goals = {
    survey:{name:'Fracture survey',description:'Break 6 enemy shields during this voyage.',target:6,metric:'breaks',battle:'Break 2 enemy shields.',battleTarget:2},
    resonance:{name:'Resonance study',description:'Trigger 6 elemental chains during this voyage.',target:6,metric:'chains',battle:'Trigger 2 elemental chains.',battleTarget:2},
    safe:{name:'Safe recovery',description:'Win 3 encounters without a crew member going Down.',target:3,metric:'safeWins',battle:'Win without a crew member going Down.',battleTarget:1}
  };
  const route=['First contact','Echo basin','Major enemy','Deep survey','Major enemy','Final extraction'];
  const tags={Hull:['Barriers +45%.','Absorbed damage becomes ammunition.'],Blight:['Fracture applications add 1 stack.','Periodic Blight detonations activate.'],Drive:['Crew act 12% faster.','Kills advance the next ally.'],Ordnance:['Crew direct damage +20%.','A hit that breaks a shield lands twice.'],Assay:['Shield damage +60%.','A Break makes the enemy skip two turns.'],Crew:['Healing +50%.','One emergency relief per encounter.']};
  function activeModifiers(state){return [...new Set(state.modifiers||[])].filter(id=>modifiers[id]);}
  function effects(state){const out={enemyHp:1,enemyDamage:1,crewDamage:1,reward:1,packCost:0,flatGold:0};activeModifiers(state).forEach(id=>{const m=modifiers[id];['enemyHp','enemyDamage','crewDamage','reward'].forEach(k=>out[k]*=m[k]||1);out.packCost+=m.packCost||0;out.flatGold+=m.flatGold||0;});return out;}
  function planetCounts(names){const counts={};[...new Set(names)].forEach(n=>{if(crew[n])counts[crew[n].planet]=(counts[crew[n].planet]||0)+1});return counts;}
  function planetHealth(names){return 1+Object.values(planetCounts(names)).reduce((sum,n)=>sum+(n>=3?.15:n>=2?.08:0),0);}
  function goal(state){return goals[state.goal]||goals.survey;}
  function goalGain(state,result){const g=goal(state);return g.metric==='safeWins'?(result.won&&result.deaths===0?1:0):Math.max(0,Number(result[g.metric])||0);}
  function observed(state,stats,won){const g=goal(state);return g.metric==='safeWins'?won&&stats.deaths===0:(stats[g.metric]||0)>=g.battleTarget;}
  window.SpacologyExpedition={crew,summons,worlds,shipParts,recipes,modifiers,goals,route,tags,activeModifiers,effects,planetCounts,planetHealth,goal,goalGain,observed,rowSlots:{field:5,support:7},recruitCost:32,attuneScrap:12,attuneCrystals:1};
})();
