/* Shared, keyboard-accessible game menus for the Ops room and live battles. */
(function(){
  'use strict';
  let adapter={},dialog,screen='pause',origin='pause',pending=false,confirmAction=null,confirmBack=null;
  let preferences=SpacologyPreferences.load();
  const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const $=id=>document.getElementById(id);
  function apply(){document.documentElement.classList.toggle('reduce-motion',preferences.reducedMotion);adapter.applyPreferences?.(preferences);}
  function summary(){const s=adapter.state?.();if(!s)return '';const n=window.SpacologyVoyage?.current(s);return `<div class="menu-voyage"><span class="menu-kicker">${s.end?'VOYAGE ENDED':s.round>s.maxRounds?'VOYAGE COMPLETE':adapter.mode==='battle'?'FIELDWORK IN PROGRESS':'YOUR VOYAGE'}</span><h3>${escape(n?.name||'Star Singer expedition')}</h3><p>${escape(SpacologyVoyageSettings.difficulties[s.difficulty]?.label||'Standard')} · Node ${Math.min(s.round,s.maxRounds)} / ${s.maxRounds}</p><div class="menu-stat-row"><span><b>${s.integrity}%</b> integrity</span><span><b>${s.gold}</b> gold</span><span><b>${s.battlesWon||0}</b> victories</span></div></div>`;}
  function frame(title,content,{back=true,eyebrow='STAR SINGER · FLIGHT SYSTEMS',wide=false}={}){
    dialog.classList.toggle('menu-wide',wide);
    dialog.innerHTML=`<header class="menu-heading"><div><span class="menu-kicker">${eyebrow}</span><h2 id="gameMenuTitle">${title}</h2></div>${back?'<button class="menu-icon" data-menu="back" aria-label="Back">←</button>':''}</header>${content}`;
    if(!dialog.open)dialog.showModal();
    requestAnimationFrame(()=>dialog.querySelector('[autofocus],button,select,input')?.focus());
  }
  function init(options){adapter=options;dialog=document.createElement('dialog');dialog.id='gameMenu';dialog.className='game-menu';dialog.setAttribute('aria-labelledby','gameMenuTitle');document.body.appendChild(dialog);
    dialog.addEventListener('cancel',e=>{e.preventDefault();if(!pending)back();});
    dialog.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const items=[...dialog.querySelectorAll('button:not(:disabled),select:not(:disabled),input:not(:disabled),a[href]')].filter(el=>el.getClientRects().length);const first=items[0],last=items[items.length-1];if(!first){e.preventDefault();return}if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});
    dialog.addEventListener('click',click);
    dialog.addEventListener('change',e=>{const key=e.target.dataset.preference;if(!key)return;const next={...preferences,[key]:e.target.type==='checkbox'?e.target.checked:e.target.value};preferences=SpacologyPreferences.save(next);apply();adapter.preferenceChanged?.(key,preferences);const status=$('preferenceStatus');if(status)status.textContent='Settings saved';});
    document.addEventListener('keydown',e=>{if(e.key!=='Escape'||dialog.open||e.defaultPrevented||document.querySelector('dialog[open],.overlay.open'))return;if(adapter.canPause?.()===false)return;e.preventDefault();openPause();});
    apply();return api;
  }
  async function openPause(){if(dialog.open||pending||adapter.canPause?.()===false)return;origin='pause';screen='pause';pending=true;frame('Pausing…','<p class="menu-copy" role="status">Finishing the current action and saving your place.</p>',{back:false});
    try{await adapter.pause?.();pending=false;if(adapter.canPause?.()===false){close();return}pauseScreen();}catch(error){pending=false;frame('Unable to save','<p class="menu-copy">Your game is still open. Free some device storage before leaving.</p><button class="menu-primary" data-menu="resume">BACK TO GAME</button>',{back:false});}
  }
  function pauseScreen(){screen='pause';frame(adapter.mode==='battle'?'Battle paused':'Voyage paused',`<div class="pause-layout"><nav class="menu-actions" aria-label="Pause menu"><button class="menu-primary" data-menu="resume" autofocus>RESUME GAME <kbd>Esc</kbd></button><button data-menu="settings">SETTINGS</button><button data-menu="help">HOW TO PLAY</button><button data-menu="home">SAVE & MAIN MENU</button>${adapter.retreat?'<button class="menu-danger" data-menu="retreat">RETREAT FROM VOYAGE</button>':''}</nav><div>${summary()}<p class="menu-note">${adapter.mode==='battle'?'Combat is paused. Your current battle is saved.':'Your formation, supplies and progress are saved on this device.'}</p></div></div>`,{back:false});}
  function close(resume=false){dialog.close();screen='';if(resume)adapter.resume?.();}
  function back(){if(screen==='departure'){close();adapter.departBack?.();return}if(screen==='confirm'){const fn=confirmBack;confirmAction=null;fn?.();return}if(screen==='pause'){close(true);return}if(origin==='pause'){pauseScreen();return}close();if(origin==='title')adapter.titleFocus?.();}
  function select(key,label,description,options,disabled=false){return `<label class="menu-setting"><span><b>${label}</b><small>${description}</small></span><select data-preference="${key}" ${disabled?'disabled':''}>${options.map(([id,name])=>`<option value="${id}" ${String(key==='recovery'&&adapter.state?.()?SpacologyDownRecovery.mode(adapter.state()):preferences[key])===String(id)?'selected':''}>${name}</option>`).join('')}</select></label>`;}
  function toggle(key,label,description){return `<label class="menu-setting"><span><b>${label}</b><small>${description}</small></span><input type="checkbox" data-preference="${key}" ${preferences[key]?'checked':''}></label>`;}
  function settings(from){if(from)origin=from;screen='settings';const s=adapter.state?.(),recoveryLocked=adapter.mode==='battle'||!!SpacologyPreferences.readCheckpoint(s);frame('Settings',`<p class="menu-copy">Preferences are saved automatically and shared across voyages.</p><div class="menu-settings"><section><h3>Combat & display</h3>${select('speed','Battle speed','Changes presentation speed, not combat time.',[[1,'1× · Normal'],[1.5,'1.5× · Fast'],[2,'2× · Fastest']])}${select('effects','Particle effects','Choose how much visual detail to show.',[['full','Full'],['low','Low'],['off','Off']])}${toggle('reducedMotion','Reduce motion','Removes combat movement, flashes and screen shake.')}${toggle('autoBattle','Auto-start battles','Begin playing when entering a new battle.')}${toggle('pauseOnHide','Pause in background','Pause combat when you switch tabs or apps.')}</section><section><h3>Voyage defaults</h3>${select('recovery','Downed crew',recoveryLocked?'Change this between battles.':'Applies to your next battle and new voyages.',[['lastStand','Last Stand'],['revive','Recover'],['none','No recovery']],recoveryLocked)}<p class="menu-note">Last Stand prevents a lethal hit once per crew member. Recover restores 50% health at a cost of half a combat round each time.</p>${s?.voyageStarted||s?.voyageVersion===0?`<div class="menu-rule-summary"><b>${escape(SpacologyVoyageSettings.difficulties[s.difficulty]?.label)} difficulty · locked</b><p>${(SpacologyExpedition.activeModifiers(s).map(id=>escape(SpacologyExpedition.modifiers[id].name)).join(' · ')||'No optional voyage modifiers')}</p>${adapter.voyageRules?'<button data-menu="rules">VIEW VOYAGE RULES</button>':''}</div>`:'<p class="menu-note">Choose difficulty when you start a new voyage.</p>'}</section></div><footer class="menu-footer"><span id="preferenceStatus" role="status">Saved on this device</span><button data-menu="reset-settings">RESTORE DEFAULTS</button><button class="menu-primary" data-menu="back">DONE</button></footer>`,{wide:true});}
  function help(from){if(from)origin=from;screen='help';frame('A field guide to the voyage',`<div class="menu-guide"><article><span>01</span><h3>Prepare your crew</h3><p>Spend gold on packs, deploy crew to the front and back rows, and equip gear. Front-row crew take enemy attacks; back-row crew provide support.</p></article><article><span>02</span><h3>Explore three sectors</h3><p>Each sector has seven stops: battles, rewards, a modifier choice and a boss. The first reward helps you build your team. Strength increases after each boss.</p></article><article><span>03</span><h3>Bring something home</h3><p>Break enemy shields by matching weaknesses. Clear the field before the combat deadline. Partial recovery still returns data and gold. Defeat treasure carriers for extra loot, then open their caches in Ops.</p></article></div><div class="menu-controls"><b>Controls</b><p>Tap or click crew, equipment and enemies for details. Drag crew to deploy them. <kbd>Esc</kbd> opens or closes the pause menu; <kbd>Space</kbd> toggles battle playback.</p></div><button class="menu-primary" data-menu="back">GOT IT</button>`,{wide:true});}
  function confirm({title,copy,actionLabel,onConfirm,onCancel}){screen='confirm';confirmAction=onConfirm;confirmBack=onCancel||pauseScreen;frame(title,`<p class="menu-copy">${escape(copy)}</p><div class="menu-confirm-actions"><button data-menu="cancel" autofocus>GO BACK</button><button class="menu-danger" data-menu="confirm">${escape(actionLabel)}</button></div>`,{eyebrow:'VOYAGE CONTROL'});}
  function departure(onStart,onBack){origin='title';screen='departure';adapter.depart=onStart;adapter.departBack=onBack;const selected=adapter.state?.()?.difficulty||'standard';frame('Chart a new voyage',`<p class="menu-copy">Three sectors. Twenty-one stops. Choose the conditions your crew will face.</p><div class="menu-difficulties">${Object.entries(SpacologyVoyageSettings.difficulties).map(([id,d])=>`<button data-difficulty="${id}" class="difficulty-card ${id===selected?'selected':''}" aria-pressed="${id===selected}"><span class="menu-kicker">${id==='relaxed'?'ROOM TO EXPERIMENT':id==='hard'?'A TOUGHER EXPEDITION':'THE STANDARD EXPEDITION'}</span><h3>${d.label}</h3><p>${Math.round(d.enemyScale*100)}% enemy health & damage<br>${Math.round(d.enemySpeed*100)}% enemy speed<br>${Math.round(d.enemyGuard*100)}% shield strength</p><small>${id==='relaxed'?7:id==='hard'?5:6} rounds per early battle<br>${Math.round(d.breakDelay*100)}% enemy delay on break</small><span class="difficulty-check" aria-hidden="true">${id===selected?'✓':'○'}</span></button>`).join('')}</div><p class="menu-note">Difficulty stays fixed. Later sectors and bosses allow more combat rounds. At three stops, you can add optional voyage modifiers.</p><footer class="menu-footer"><button data-menu="cancel-departure">BACK</button><button class="menu-primary" data-menu="depart">BEGIN VOYAGE →</button></footer>`,{wide:true,back:false,eyebrow:'DEPARTURE · STAR SINGER'});}
  async function click(e){const b=e.target.closest('button');if(!b||pending)return;
    if(b.dataset.difficulty){dialog.querySelectorAll('[data-difficulty]').forEach(x=>{const selected=x===b;x.classList.toggle('selected',selected);x.setAttribute('aria-pressed',String(selected));x.querySelector('.difficulty-check').textContent=selected?'✓':'○';});return}
    switch(b.dataset.menu){
      case 'back':back();break;
      case 'resume':close(true);break;
      case 'settings':settings();break;
      case 'help':help();break;
      case 'home':await adapter.home?.();break;
      case 'retreat':confirm({title:'End this voyage?',copy:'Your crew will retreat. Completed rewards stay in the inbox, but this voyage cannot continue. Unclaimed pack cards are lost.',actionLabel:'END VOYAGE',onConfirm:()=>{close();adapter.retreat?.();}});break;
      case 'cancel':back();break;
      case 'confirm':{const fn=confirmAction;confirmAction=null;await fn?.();break;}
      case 'rules':close();adapter.voyageRules?.();break;
      case 'reset-settings':confirm({title:'Restore default settings?',copy:'This resets presentation and recovery preferences. Your voyage, difficulty and rewards are preserved.',actionLabel:'RESTORE DEFAULTS',onCancel:()=>settings(),onConfirm:()=>{preferences=SpacologyPreferences.save(SpacologyPreferences.defaults);apply();adapter.preferenceChanged?.('recovery',preferences);settings();}});break;
      case 'cancel-departure':close();adapter.departBack?.();break;
      case 'depart':{const choice=dialog.querySelector('[data-difficulty][aria-pressed="true"]').dataset.difficulty;await adapter.depart?.(choice);break;}
    }
  }
  const api={init,openPause,settings,help,confirm,departure,close,isOpen:()=>!!dialog?.open,preferences:()=>({...preferences})};
  window.SpacologyMenu=api;
})();
