/* Dedicated Weaver identities and combat definitions. Loaded after expedition-rules. */
(function(root){
  'use strict';
  const crew={
    Hanae:{fullName:'Hanae Mori',age:46,pronouns:'she/her',element:'energy',tags:['Assay','Drive'],planet:'Tannhul VI',species:'Porcelain stoneskin',birthplace:'Tannhul VI resonance terraces',position:'both',stats:{hp:118,dmg:20,speed:11},portrait:'../assets/cast/hanae-mori-v3.png',weaver:'Gatherer',role:'Resonance collector',summary:'An acoustician whose gold repairs catch the energy other instruments discard.',
      lore:["Hanae spent twenty years listening for cracks in the load-bearing terraces of Tannhul VI. When a survey platform failed, the repairs to her own stone skin acquired an inconvenient property: every stressed seam sang. She learned to distinguish pain from a useful signal, and eventually built an instrument that could return those signals as usable Aether. She calls the result a conversation, not a cure.","She is short, sturdy, loud when amused and exacting when someone handles her instruments. On Star Singer she records a different room each morning. Roonie tries to identify it from the recording; she sometimes includes the sound of his own snoring. She and Veska disagree about whether a perfectly repeatable note is a success. Her private ambition is to record the ship at rest, though she has never heard it entirely quiet."],
      kit:{attack:['Sounding Knock','125% attack and guard pressure. Generates 2 Aether.'],basic:['Pass the Chord','Spend 1 Aether, hit one specimen for 200% attack and mark it, then restore 5 Aether (+4 net, capped by the pool). Another ally’s next basic gathers +1 Aether; does not stack.'],skill:['Every Seam Sings','Hit every specimen for 300% attack, apply 2 survey marks and restore 4 shared Aether. Uses individual ultimate charge.'],passive:['Golden Repairs','Her basics generate 2 Aether instead of 1.'],plan:'Auto uses her skill when the pool has room for a refill. Her +4 net skill and +4 ultimate fund Arunima’s burst; at zero Aether, basic first.'},combat:{p:'breaker',marks:1,ult:{name:'Every Seam Sings',kind:'aoe',mult:3,survey:2,aether:4}}},
    Ivara:{fullName:'Ivara',age:'adult',pronouns:'he/him',element:'void',tags:['Hull','Crew'],planet:'Iseul III',species:'Synthetic narwhal',birthplace:'Iseul III orbital salvage dock',position:'both',stats:{hp:132,dmg:16,speed:9},portrait:'../assets/cast/void-narwhal-navigator-v1.png',weaver:'Reservoir',role:'Echo reservoir and route shelter',summary:'A synthetic navigator who makes room for signals that no longer have a destination.',
      lore:["Ivara was recovered from a relay buoy still announcing a route that had ceased to exist. His makers had given him an exquisitely sensitive spiral receiver and enough memory to hold a convoy’s return paths. They had not given him an instruction for what to do when nobody came back. He spent eleven years keeping the channel open before Navigator persuaded him that leaving was not the same as forgetting.","His original narwhal machine body is a deliberate, singular design: ivory plates, listening fins and a luminous spiral horn. He speaks softly and uses he/him. Aether storage is the practical use of the quiet intervals he preserves between echoes; his shelter briefly removes a threatened ally from an incoming hit’s route. He repairs cracked mugs without being asked and has recently begun choosing which distress recordings he wishes to keep. Arunima never calls his empty channels wasted space."],
      kit:{attack:['Echo Probe','125% attack. Generates 1 Aether.'],basic:['Unwritten Shelter','The most injured on-field ally ignores their next direct incoming hit. The shelter does not stack.'],skill:['Safe Anchorage','Grant every living ally 24 barrier and restore 6 shared Aether. Uses individual ultimate charge.'],passive:['Room for an Echo','Adds 2 extra shared Aether capacity while alive, on top of the 1 granted by every deployed Weaver; does not add starting charges.'],plan:'His larger pool lets you bank a burst. Shelter protects the front while your gatherers work.'},combat:{p:'breaker',taunt:1.5,ult:{name:'Safe Anchorage',kind:'mend',amt:0,barrier:24,aether:6}}},
    Arunima:{fullName:'Arunima Das',age:63,pronouns:'she/her',element:'void',tags:['Assay','Ordnance'],planet:'Iseul III',species:'Rift-elf',birthplace:'Iseul III folded-orbit archive',position:'support',stats:{hp:98,dmg:28,speed:8},portrait:'../assets/cast/arunima-das-v4.png',weaver:'Conduit',role:'Topological burst and control',summary:'A cartographer who spends stored charge to remove the distance between a problem and its answer.',
      lore:["Arunima used to certify routes through Iseul’s folded orbits. Her maps were correct until a corridor changed during an evacuation. She held the exit with three hands and carried the last passenger with the fourth; the route took her leg when it closed. Her mechanical replacement is beautifully maintained, but she refuses a decorative cover because every successful journey should show what made it possible.","Tall, lean and silver-braided, she is patient with learners and intolerant of confident guesses. She joined Star Singer to map places that cannot be certified safe in advance. Ivara supplies the stored silences she uses as anchors; Hanae supplies the charge to open them. She tutors Daven with physical models and insists his inability to complete a timed written proof says nothing about his judgment. She keeps a blank page for the person who will correct her best map."],
      kit:{attack:['Find the Seam','125% attack and one survey mark. Generates 1 Aether.'],basic:['Proof by Transit','Spend 3 Aether to hit every specimen for 300% attack and delay each by 15 AV. With Full burst enabled, spend available Aether up to the current pool capacity: each extra charge adds 100 percentage points of attack damage and more guard pressure, reaching 800% at 8 or 1400% at 14. Auto spends less when a smaller hit can clear the current enemies. Respects another ally’s reservation. Roonie’s discount saves 1 charge without reducing damage.'],skill:['No Distance Remains','Hit every specimen for 500% attack and apply 2 survey marks. Uses individual ultimate charge.'],passive:['Wider Aperture','Full burst turns each extra Aether spent into a larger attack multiplier, scaling with the current pool capacity. It spends the available budget in one hit per specimen.'],plan:'Enable Full burst for the payoff: 8 Aether becomes an 800% attack; 14 becomes 1400%. Hanae refills with skills, Ivara refills with his ultimate, and Roonie makes the same burst cost 1 less.'},combat:{p:'breaker',marks:1,aoe:1,ult:{name:'No Distance Remains',kind:'aoe',mult:5,survey:2}}},
    Roonie:{fullName:'Roonie Baelk',age:16,pronouns:'he/him',element:'energy',tags:['Drive','Crew'],planet:'Earth',species:'Axolotl amphiboid',birthplace:'Earth orbital wet-habitat community',position:'support',stats:{hp:94,dmg:15,speed:12},portrait:'../assets/cast/roonie-baelk-v7.png',weaver:'Tuner',role:'Apprentice conduit technician',summary:'A young repairer whose improbable little machines make scarce charges go further.',
      lore:["Roonie grew up in a wet-habitat maintenance family, taking apart the devices that told everyone else to stop taking things apart. His first independent robot delivered a replacement valve to the wrong apartment every morning for a month. He kept fixing its navigation until the recipient asked if it could stay. On Star Singer he is an apprentice, with supervised field duty and schoolwork that does not disappear when a manifold becomes interesting.","He has a human teenage face and lanky body, pale speckled amphibian skin and conspicuous feathery axolotl gills and fin-shaped amphiboid ears. His gills flare when a circuit finally works, making it impossible to pretend he knew it would. Hanae helps him hear losses in a conduit, and Daven checks every isolation switch before letting him touch it. Roonie wants to make useful machines that people can repair themselves; he is quietly offended by sealed housings."],
      kit:{attack:['Continuity Tap','125% attack. Generates 1 Aether. Every second basic tunes another ally’s next skill.'],basic:['Borrow My Bypass','Give another ally 10 barrier and reduce their next skill cost by 1 Aether, to a minimum of 1. Does not stack.'],skill:['All Circuits Clear','Restore 12 health and 25 individual ultimate charge to every living ally, including Roonie. Also restore 4 shared Aether once per cast.'],passive:['Pocket Workshop','Every second basic grants one ally a non-stacking, one-use skill discount.'],plan:'Auto waits until a useful untuned ally needs a bypass; his basics still provide discounts while funding the pool.'},combat:{p:'breaker',ult:{name:'All Circuits Clear',kind:'mend',amt:12,charge:25,aether:4}}},
    Veska:{fullName:'Veska Reed',age:57,pronouns:'she/her',element:'growth',tags:['Crew','Drive'],planet:'Earth',species:'Avian humanoid',birthplace:'Earth estuary city',position:'support',stats:{hp:114,dmg:14,speed:10},portrait:'../assets/cast/veska-reed-v3.png',weaver:'Cantor',role:'Refrain healer',summary:'A shipboard singer whose quiet repetitions give a scattered crew time to recover.',
      lore:["Veska was a rehabilitation worker before anyone paid her to sing. She learned to pace exercises around a patient’s breathing, and discovered that a repeated phrase could keep a tired room working together without asking anyone to be brave. Her weekly performances aboard Star Singer began as a favor to a homesick technician. She now has a permanent evening, a terrible folding stool and an audience that pretends not to know every song.","She is tall and soft-bodied, with a human face, russet and silver plumage, feathered arms and conspicuous avian eyes. Her voice is warm rather than spectacular; she knows when to leave space for another person. Hanae measures their rehearsals, which Veska considers a peculiar form of affection. She asks Ivara for sounds he remembers rather than sounds he can reproduce. Her healing builds a refrain through ordinary work, then releases what the crew has patiently gathered."],
      kit:{attack:['Keep the Refrain','125% attack. Generates 1 Aether and builds one Refrain, up to 3.'],basic:['One More Verse','Heal every living ally for 12 health plus 6 per Refrain, then consume all Refrains and restore 1 shared Aether per Refrain (up to 3). Healing harmonies apply.'],skill:['The Room Sings Back','Restore 36 health to every living ally. Uses individual ultimate charge.'],passive:['Practiced Together','Each basic builds one Refrain; her next skill turns those repetitions into stronger healing and returns up to 3 Aether.'],plan:'Auto builds while the crew is healthy, and spends when someone falls below 75% health. Build mode still permits emergency healing.'},combat:{p:'breaker',ult:{name:'The Room Sings Back',kind:'mend',amt:36}}},
    Daven:{fullName:'Daven Pell',age:44,pronouns:'he/him',element:'order',tags:['Hull','Crew'],planet:'Earth',species:'Marble stoneskin',birthplace:'Earth orbital vocational district',position:'field',stats:{hp:174,dmg:18,speed:8},portrait:'../assets/cast/daven-pell-v7.png',weaver:'Anchor',role:'Barrier technician and recovery anchor',summary:'Eight failed examinations have not stopped the crew trusting him with the emergency shutoff.',
      lore:["Daven has failed the same advanced certification eight years running. In a timed examination he loses his place, revises correct answers and runs out of paper. In a failing pressure chamber he checks the exit, finds the actual fault and tells everyone exactly what to do. He is already qualified for his shipboard work; the examination is the promotion he wants, not permission he has been working without.","Broad, fat and strong, with a bare veined-marble crown, layered angular marble locks at the sides of his head, a carved mineral beard and a patient human face, he carries a workbook whose pages have been replaced more often than its cover. Arunima teaches him with hinged models. Roonie draws circuits in the margins, then asks for help with the parts that must be safe. Daven’s barriers are ordinary, precise engineering. His gift is recovering a useful charge from an impact without letting the impact become somebody else’s problem. He intends to sit the examination again."],
      kit:{attack:['Check the Brace','125% attack and 6 personal barrier. Generates 1 Aether.'],basic:['Hold the Line','Hit one specimen for 225% attack, gain 32 personal barrier and draw more attacks until his next turn.'],skill:['Everyone Behind Me','Grant every living ally 40 barrier. Uses individual ultimate charge.'],passive:['Recovered Load','The first enemy hit absorbed by his barrier between his turns returns 1 Aether. Requires Daven to survive; capped by the shared pool.'],plan:'Keep him on field. His own barriers let him return a little charge while protecting the gatherers.'},combat:{p:'breaker',taunt:2,ult:{name:'Everyone Behind Me',kind:'mend',amt:0,barrier:40}}}
  };
  Object.assign(root.SpacologyExpedition.crew,crew);
  root.SpacologyWeavers={crew,names:Object.keys(crew)};
})(window);
